[packages]
python = "3.11"
gcc = "*"
libpq = "*"
libpng = "*"
freetype = "*"
pkgconfig = "*"
libffi = "*"
openssl = "*"
zlib = "*"
tk = "*"

[commands]
install = "pip install --upgrade pip && pip install -r requirements.txt"

[start]
command = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
